version: "3.8"

services:
    web:
        build: .
        command: uvicorn main:app --reload --host "0.0.0.0" --port 8000
        container_name: "wishlist"
        env_file:
            - .env
#        environment:
#            - DATABASE_URL=postgresql://gabriel:root@127.0.0.1/wishlist
        volumes:
            - .:/app
        ports:
            - 8000:8000
        depends_on:
            - db
    db:
        image: postgres:13
        container_name: "wishlist_postgres"
#        ports:
#            - 5432:5432
        expose:
            -   5432
#        networks:
#            - postgres
        environment:
            - POSTGRES_USER=gabriel
            - POSTGRES_PASSWORD=root
            - POSTGRES_DB=postgres
        volumes:
            - postgres_data:/var/lib/postgres/data/

volumes:
    postgres_data:

#networks:
#    postgres:
